### ISSUE TITLE
Line details with HighCharts

### ISSUE THREAD

**Issue by caclement** [RamezIssac/django-slick-reporting#104]
Hello

It seems there is a bug when generating a LINE chart with highchart.

It seems the demo website has the same error, with the Total Sales [Line total] and Total Sales [Line details]

https://django-slick-reporting.com/highcharts-examples/

`
Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=
 - missingModuleFor: 
    at Object.<anonymous> (highcharts.js:8:138)
    at M (highcharts.js:8:2591)
    at o (highcharts.js:8:61)
    at Q.initSeries (highcharts.js:8:195148)
    at highcharts.js:8:210172
    at Array.forEach (<anonymous>)
    at Q.firstRender (highcharts.js:8:210150)
    at Q.<anonymous> (highcharts.js:8:195066)
    at M (highcharts.js:8:2591)
    at Q.init (highcharts.js:8:194484)
`

**Comment by RamezIssac** [comment]
Hello @caclement 

Today i issued a release 1.3.1 fixing this issue and updated it on the demo site.
Thank you for the report and let me know if you find any other issues .
